### ISSUE TITLE
[Suggestion] Allow custom action creator prefix

### ISSUE THREAD

**Issue by iamchanii** [epeli/immer-reducer#12]
Hi! I like this awesome library as typescript user with react.

I hope to customize action type prefix. but now, the prefix is constraint value (`"IMMER_REDUCER"`)
I suggest allow custom action type's prefix, so user can customize that.

so, I did it on my forked repository:
https://github.com/iamchanii/immer-reducer/commit/735f58e14917444add14ddb65d7816ee10a72837

i think maybe it makes offend you. This suggest may prevent the prefix IMMER_REDUCER from being seen in the user's application. but if you don't mind it and you want this suggest, I will submit a PR happily!

**Comment by epeli** [comment]
It's cool! So PR welcome 😊

**Comment by iamchanii** [comment]
> It's cool! So PR welcome 😊

Thanks for your reaction! I will submit right now.
