### ISSUE TITLE
Unreadable parameters type

### ISSUE THREAD

**Issue by user753** [epeli/immer-reducer#2]
```
const initialState = {foo: "bar"};
class TestReducer extends ImmerReducer<typeof initialState> {
    setFoo(foo: string) {
        this.draftState.foo = foo;
    }
}

const ActionCreators = createActionCreators(TestReducer);
ActionCreators.setFoo()
```
![screenshot from 2018-11-20 17-45-22](https://user-images.githubusercontent.com/35331542/48780989-21e6a200-ecec-11e8-943c-5d54e995dbb2.png)
Is it possible to do so it would be `foo: string`?

**Comment by epeli** [comment]
Interesting. VSCode seems to behave bit differently depending on where the autocomplete popup is opened.

Before the parens it shows this

![image](https://user-images.githubusercontent.com/225712/48805417-01383f80-ed20-11e8-8ab1-2264636812e4.png)

which is what you are asking for.

But after adding parens

![image](https://user-images.githubusercontent.com/225712/48805341-cc2bed00-ed1f-11e8-8bda-7767a997bd28.png)

it gets bit dirtier by showing the arguments type as a tuple.

But then again by hovering the method:

![image](https://user-images.githubusercontent.com/225712/48805655-920f1b00-ed20-11e8-8ae6-bfb25565af4c.png)

proper arguments type is show.

---

I'm not able to reproduce your situation where only the generics name shown.

What Typescript and VSCode versions are you using?

My examles are with TS 3.1.6 and VScode 1.29.0.

**Comment by user753** [comment]
It's WebStorm. So I guess it's a problem on their side.

**Comment by epeli** [comment]
Probably but I'd still encourage you to check what Typescript version are using in WebStorm because usually Typescript autocompletions are not provided by the IDE but the Typescript language server which comes with the Typescript compiler. So just upgrading Typescript might fix it for WebStorm too.

**Comment by user753** [comment]
3.1.6
I think they use some additional logic over language server
