### ISSUE TITLE
Consider exposing composeReducers

### ISSUE THREAD

**Issue by Secretmapper** [epeli/immer-reducer#31]
Due to the nature of how immer-reducer works (working on arbitrary pieces of state), composing reducers is pretty much the direction in which the reducers would be created.

I think due to this, it might be a good idea to consider exposing composeReducers as a utility inside the library. It could even be put such that tree-shaking will remove it if unused. Happy to put in a PR if you think it's not out of scope

**Comment by epeli** [comment]
Yes, PR welcome!

**Comment by Secretmapper** [comment]
Any chance we can publish this in a new version :)

**Comment by epeli** [comment]
Out with v0.7.6!

Sorry, it took a while. I was on vacation without npm credentials :)

**Comment by Secretmapper** [comment]
No worries, Cheers!
