### ISSUE TITLE
Replacing draftState completely

### ISSUE THREAD

**Issue by skoshy** [epeli/immer-reducer#37]
Is there a way to replace the `draftState` with a new state? See the [immer Readme](https://github.com/immerjs/immer/blob/master/readme.md#returning-data-from-producers) for an example

Key line is here:

> It is also allowed to return arbitrarily other data from the producer function. But only if you didn't modify the draft. This can be useful to produce an entirely new state.

Can the same be done with functions in an ImmerReducer? My use case is to completely reset the state back to the original state. The alternative I'm doing is looping through all the keys of `this.draftState` and setting those equal to the initial state.

**Comment by epeli** [comment]
Just added this in the latest [release](https://github.com/epeli/immer-reducer/releases/tag/v0.7.6)

You can do `this.draftState = newState` which is the same as returning new state from the immer produce-function.

Should add this bit to README...
